# Generated by Django 2.2.3 on 2019-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('relation_posts', models.ManyToManyField(blank=True, related_name='_post_relation_posts_+', to='app.Post', verbose_name='関連記事')),
            ],
        ),
    ]
